spring:
  application:
    name: EventClean

  datasource:
    url: jdbc:postgresql://localhost:5432/eventclean
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

    flyway:
      enable: true
      locations: classpath:db/migration
